### ISSUE TITLE
Implement EDI 867

### ISSUE THREAD

**Issue by chris1610** [glitchassassin/python-edi#1]
First off, thanks for pulling this together. I think it does exactly what I'm looking for - implementing an Excel to EDI 867 converter. I wanted to get a feel for your plans on taking on other EDI types.

I spent some time manually looking at the 810.json file and have some thoughts about how to convert but figured I'd ask you and see if you already have anything already in place for 867 or any plans for this message type?

If you don't have anything, do you have any pointers on how to most efficiently/quickly get 867 up and running?

Thanks again!

**Comment by glitchassassin** [comment]
An editor with multiline editing was my best friend when putting the 810.json file together. =)

I'd like to think the 810 file is fairly self-documenting, so you should have most of what you need to adapt it to a new format. If you do run into questions, let me know!

**Comment by chris1610** [comment]
Thanks. I spent some time working on it and most of it makes sense but I'm trying to figure out the looping component for PTD. It seems like there is a loop for PTD, N1 and QTY but I'm not quite sure how to nest them. Do you mind pointing me to where the spec you used for 810? That might help me out.

**Comment by glitchassassin** [comment]
I referred to a couple which were slightly different, but this was the primary one:

[810_ANSI_X12_122007_001.pdf](https://github.com/glitchassassin/python-edi/files/2352741/810_ANSI_X12_122007_001.pdf)

The general idea with loops is that each loop can have zero or more of each segment in the loop spec's `segments` list (controlled by the segment's `req` and `max_uses` values). What are you running into with the 867 spec?

**Comment by chris1610** [comment]
Ok. This helps. The 867 spec has a 3 level nested loo: PTD, N1 and QTY. After seeing this example, I think I understand how to pull it together. Thanks.

**Comment by rabbu786** [comment]
Hi,
I need small help
Please let me know the steps how I can run this project(to generate the edi format)
Please help me to get edi format

**Comment by glitchassassin** [comment]
Hi @rabbu786! Check out the test file for an example of how to set up and generate an EDI-formatted message from a Python object: https://github.com/glitchassassin/python-edi/blob/master/test/test_pythonedi.py

**Comment by rabbu786** [comment]
Thank you for your response
Please share with me if you are having Python code to generate Edi 835
format.
It will be more helpful to us.


Thanks & Regards,
Rabbani Shaik,
Mobile:2248041327

**Comment by glitchassassin** [comment]
Nope, but you are welcome to copy one of the existing definitions and submit a PR!

E.g. https://github.com/glitchassassin/python-edi/blob/master/pythonedi/formats/850.json
